### ISSUE TITLE
buffer#to_string gives buffer word count in string?

### ISSUE THREAD

**Issue by wiredsister** [fxfactorial/ocaml-nodejs#3]
With a json file like: 

``` javascript

{
    "name" : "Eridin, Destroyer of Worlds",
    "description" : "It is unavoidable.",
    "deck" : "Monsters",
    "combat row" : "Not applicable",
    "strength" : "Not applicable",
    "special ability" : "Destroyer of Worlds"
}

```

I've got some code like: 

``` ocaml

let my_json_example : Yojson.Safe.json =
  try
    match Nodejs.Fs.read_file_sync "example.json" with
    | String s -> Yojson.Safe.from_string s
    | Buffer b -> b#to_string () |> Yojson.Safe.from_string
  with e -> raise e

```

When I print that, I'm getting the number 32. When I `wc` on that, I see that it's printing the word count of that buffer plus a new line character. When I do `int_of_string (buffer#length) |> Yojson.Safe.from_string` on that, I get the number 2 weirdly. 

Example: 

``` bash

$ wc example.json 
8  31 233 example.json

```

Pretty sure the bindings have some bugs here: 

``` ocaml

  (* ...inside Buffer *)
    method to_string ?(encoding=Utf_8) ?(start=0) ?end_ () : string =
      (match end_ with
       | None ->
         [|to_js_str (string_of_encoding encoding); i start; i self#length|]
       | Some (j : int) ->
         [| to_js_str (string_of_encoding encoding); i start; i j|])
      |> m raw_js "toString" |> Js.to_string

```

If I can figure this out, I'll PR the fix. What's a good work around in the meantime and can you reproduce? 
Thanks.

**Comment by fxfactorial** [comment]
@wiredsister 

Thanks for the bug report!

Its probably a missing/misplaced `Js.to_string` in the bindings. I will try to fix/reproduce as well.

The real fix is the replace the regular ADT, aka the type `str_or_buf` with a GADT, the same way that `Lwt_io` uses GADTs: 

https://github.com/ocsigen/lwt/blob/master/src/unix/lwt_io.mli#L67

**Comment by fxfactorial** [comment]
@wiredsister Okay, so some findings. I don't think its buffer itself, probably the mistake is with `read_file_sync` itself given this example:

```
let t = new Buffer.buffer (`String "Hello World")

let () =
  t#to_string ()
  |> String.capitalize
  |> print_endline
```

curiously enough the prints out `Hello World`, so why its not capitalizing is like a question for `js_of_ocaml` itself methinks.

**Comment by fxfactorial** [comment]
Ah, this line is suspicious:

`Buffer (new Buffer.buffer (m fs_module "readFileSync" [|to_js_str file|]))` in read_file_sync. Not sure why the type checker isn't yelling about buffer not being of type init_t, maybe because the `m` function gives back a type variable so it unifies. The whole buffer thing needs to be redone.

**Comment by wiredsister** [comment]
@fxfactorial, I think in your example above,
`String.capitalize "Hello World"` would correctly give back `"Hello World"`. `String.uppercase "Hello World"` would give back `"HELLO WORLD"`.

**Comment by fxfactorial** [comment]
@wiredsister This fixes it.

line 1164 is: 
      `Buffer (new Buffer.buffer (m fs_module "readFileSync" [|to_js_str file|]))`

but should be:
      `Buffer (new Buffer.buffer (`String (m fs_module "readFileSync" [|to_js_str file|])))`

I'll give you commit access if you don't already have it to fix it directly on master, no need for PR. 

Doh, you're right about capitalize.

**Comment by wiredsister** [comment]
Awesome!!! :star: :star: :star: :star: :star: Will try!!! Thank you.

**Comment by wiredsister** [comment]
It works! Thank you. Will reference this in commit on master.

``` bash
 curl localhost:8080/testing
{
  "name": "Eridin, Destroyer of Worlds",
  "description": "It is unavoidable.",
  "deck": "Monsters",
  "combat row": "Not applicable",
  "strength": "Not applicable",
  "special ability": "Destroyer of Worlds"
}
```
