### ISSUE TITLE
Error when trying the second example of the readme file

### ISSUE THREAD

**Issue by jnavila** [fxfactorial/ocaml-nodejs#5]
The second example of the README file does not compile with the following error:

```
Error: Unbound value api_source
```

**Comment by fxfactorial** [comment]
Thank you, need to investigate. Feel free to send PR in meantime to fix.

**Comment by jnavila** [comment]
Ah ok, finally understood.

**Comment by jnavila** [comment]
Another question: Where is this `Fs` module coming from? I am new to the OCaml modules culture and I  can't find it.

**Comment by fxfactorial** [comment]
It's coming from Nodejs. The full name of the module is NodeJs.Fs, I just did an open Nodejs at the top to not have to write it all out.
